<?php 
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */

?> 

<div class="block block-category">
    <div class="block-title-category">
        <h2 class="category">Categories</h2>
    </div>   

    <div class="sidebarmenu">
<ul id="left-nav">
<?php foreach ($this->getStoreCategories() as $_category): ?>
    <?php echo $this->drawItem($_category) ?>
<?php endforeach ?>
</ul>
</div>
	</div> 



