<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<!--div class="nav-container"><div class="header_inner1"-->
    <ul id="nav">
        <?php echo $_menu ?>
    </ul>
<!--/div></div-->
<?php endif ?>
