
<div class="breadcrumb_division">
    
        <?php if($crumbs==""){ ?>
                 <ul>
			<li><a href="<?php echo $this->getUrl('') ?>"><?php echo $this->__('Home'); ?></a></li>
                 </ul>
    <?php
        }
    ?>
    	
    <?php if($crumbs && is_array($crumbs)): ?>

    <ul>
         <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?php echo $_crumbName ?>">
            <?php if($_crumbInfo['link']): ?>
                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
            <?php elseif($_crumbInfo['last']): ?>
                <strong><?php echo $this->escapeHtml($_crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
            <?php endif; ?>
            <?php if(!$_crumbInfo['last']): ?>
               
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
					 
    
    
    <?php endif; ?>
    
    
    
					<div class="social_links">
						<a href=""><img src="<?php echo $this->getSkinUrl('images/facebook_icon.gif');?>" alt="" /></a>
						<a href=""><img src="<?php echo $this->getSkinUrl('images/youtube_icon.gif');?>" alt="" /></a>
						<a href=""><img src="<?php echo $this->getSkinUrl('images/skype_icon.gif');?>" alt="" /></a>
						<a href=""><img src="<?php echo $this->getSkinUrl('images/share_icon.gif');?>" alt="" /></a>
					</div>
	</div>