<!--//RMP-->
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>

        <?php if(!$_product->isGrouped()): ?>
        <label for=""><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <input type="submit" value="<?php echo $buttonTitle; ?>"  class="button btn-cart" onclick="productAddToCartForm.submit(this)">
        <?php echo $this->getChildHtml('', true, true) ?>
   
<?php endif; ?>

