<div class="footer">
<div id="footerContent">
<div><?php echo $this->getChildHtml('footer_links');?></div>
<div style="float:left;">
<a href="http://www.magikcommerce.com/themes/">Magento Themes</a>&nbsp;&nbsp; <a href="http://www.magikcommerce.com/extensions">Magento Extensions</a>
</div></div>	
<div class="copyright">
Copyright &copy 2010 - 2011. All Rights Reserved. Designed by <a href="http://www.magikcommerce.com/" target="_blank">Magikcommerce.com</a>
</div>
</div>
