
<?php if ($this->isMsgVisible()): ?>
    <a href="#" id="<?php echo $this->getPlaceholderId() ?>" class="stock-qty">
        <?php echo $this->__('Only %s left', $this->getStockQty()) ?>
    </a>
    <table id="<?php echo $this->getDetailsPlaceholderId() ?>" class="stock-qty-details no-display">
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th><?php echo $this->__('Qty') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getChildProducts() as $childProduct) : ?>
            <?php $childProductStockQty = $this->getProductStockQty($childProduct); ?>
            <?php if ($childProductStockQty > 0) : ?>
                <tr>
                    <td><?php echo $childProduct->getName() ?></td>
                    <td><?php echo $childProductStockQty ?></td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>
        </tbody>
    </table>
    <script type="text/javascript">
    //<![CDATA[
    $('<?php echo $this->getPlaceholderId() ?>').observe('click', function(event){
        $('<?php echo $this->getDetailsPlaceholderId() ?>').toggleClassName('no-display');
        event.stop();
    });
    //]]>
    </script>
<?php endif; ?>
