
<?php
$_params = $this->getParams();
$_helper = $this->helper('authorizenet');
?>
<html>
<head>
<script type="text/javascript">
//<![CDATA[
<?php if (isset($_params['redirect'])): ?>
window.location="<?php echo $_params['redirect'] ?>";
<?php endif; ?>
<?php if (isset($_params['redirect_parent'])): ?>
window.top.location="<?php echo $_params['redirect_parent'] ?>";
<?php endif; ?>
<?php if (isset($_params['error_msg'])): ?>
window.top.directPostModel.showError("<?php echo $_params['error_msg'] ?>");
<?php if (isset($_params['x_invoice_num'])): ?>
window.top.directPostModel.successUrl="<?php echo $_helper->getSuccessOrderUrl($_params) ?>";
<?php endif; ?>
<?php endif; ?>
//]]>
</script>
</head>
<body></body>
</html>
