<?php
if(Mage::getStoreConfig('cookiealert/options/enabled'))
{
	?>
<div id="cookiealert" class="cookiealert" style="display: none;">
	<div class="message">
		<span class="cookie-title"><?php echo $this->__('Cookie Policy');?></span>
		<p>
	    	<?php echo $this->__('This website uses cookies to ensure proper functionality of the shopping cart and checkout progress. By continuing to browse the site you are agreeing to the use of cookies.');?>
	    	<a href="<?php echo $this->getCmsPageUrl(); ?>"><?php echo $this->__('Click here to learn about cookie settings.'); ?></a>
		</p>
		<p class="close">
			<a href="javascript:closeCookieAlert();"><?php echo $this->__('Close');?></a>
		</p>
	</div>
</div>
<script type="text/javascript">
function closeCookieAlert()
{
	Mage.Cookies.set('cookieAlertClosedFlag', 1, new Date(new Date().getTime() + (1000 * 60 * 60 * 24 * 364))); 
	document.getElementById('cookiealert').style.display = 'none';
}

if(!Mage.Cookies.get('cookieAlertClosedFlag'))
{
	document.getElementById('cookiealert').style.display = '';
}
</script>
	<?php
}
