<div class="page-head">
    <h3><?php echo Mage::helper('moneybookers')->__('Please pay your order now') ?></h3>
</div>
<table style="width:100%;">
    <tr>
        <td style="width:75%">
            <iframe style="width:100%; height:600px;" src="<?php echo Mage::getUrl('moneybookers/processing/placeform') ?>"></iframe>
        </td>
        <td style="text-align:center;">
            <img src="<?php echo $this->getMoneybookersLogoSrc() ?>" title="<?php echo Mage::helper('moneybookers')->__('Powered by Moneybookers') ?>" alt="<?php echo Mage::helper('moneybookers')->__('Powered by Moneybookers') ?>" />
        </td>
    </tr>
</table>
