<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-catalogsale-products">
    <div class="block">
        <div class="block-title">
            <strong><span><?php echo $this->__('Sale Products') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-list" id="widget-catalogsale-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(100) ?>" width="100" height="100" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)">
                         <?php $small_getName = strip_tags( $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name'));
							 if (strlen($small_getName) < '45') echo($small_getName);
								else {
								  echo substr($small_getName, 0, 47);
								  echo '...';
							 }
						  ?> </a>
						  </p>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
<?php endif; ?>
