
<?php if ($this->hasSamples()): ?>
    <dl class="item-options">
        <dt><?php echo $this->getSamplesTitle() ?></dt>
        <?php $_samples = $this->getSamples() ?>
        <?php foreach ($_samples as $_sample): ?>
            <dd>
                <a href="<?php echo $this->getSampleUrl($_sample) ?>" <?php echo $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':''; ?>><?php echo $_sample->getTitle() ?></a>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
