
<div class="page-title_a">
   <h2 class="page-title_a"><?php echo Mage::helper('customer')->__('You are now logged out') ?></h2>
</div>
<div class="form_background12">
<p><?php echo Mage::helper('customer')->__('You have logged out and will be redirected to our homepage in 5 seconds.') ?></p>
<script type="text/javascript">
//<![CDATA[
    setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},5000);
//]]>
</script></div>
