<div class="block block-subscribe">
    <div class="block-title">
        <h2 class="subscribe"><?php echo $this->__('Newsletter') ?></h2>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <label for="newsletter"><?php echo $this->__('Sign up for our newsletter:') ?></label>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div>
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><?php echo $this->__('Subscribe') ?></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
