
<div class="col2-set" style="overflow:hidden;"> 
<br />     
            <h4><?php echo $this->__('Address Book') ?></h4>
            <div class="manage_add"><a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a></div>                
            <div class="col-1">
                <h5><?php echo $this->__('Default Billing Address') ?></h5>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
            <div class="col-2">
                <h5><?php echo $this->__('Default Shipping Address') ?></h5>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>            
</div>
