<?php $_wishlistItem = $this->getWishlistItem(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getUpdateUrl($_wishlistItem); ?>
<ul class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><div align="left"><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><?php echo $this->__('Update Wishlist') ?></a>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
<?php if ($_compareUrl) : ?>
   <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></div></li>
<?php endif; ?>
</ul>
