<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->getChildHtml('head') ?>

    </head>                  
    <body>   
        <?php echo $this->getChildHtml('after_body_start') ?>              
        <div id="header" class="container">

            <?php echo $this->getChildHtml('header') ?> 
            <div class="clear"></div>
        </div>
        <div id="main_content" class="container">
            <div class="grid_5">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
            </div>
            <div class="clear"></div>

            <!-- center content begins-->
            <div class="center_content">
                <?php echo $this->getChildHtml('content') ?> 
            </div>
        </div>
        </div>

        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </body>                 
</html>
