<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Render_Item_Price */
?>

<?php echo $this->getCleanProductPriceHtml(); ?>

<?php /* @var $product Mage_Catalog_Model_Product */ ?>
<?php $product = $this->getProduct(); ?>
<?php $finalPrice = $product->getFinalPrice(1); ?>
<?php if ($product->canConfigure()): ?>
    <p class="configured-price">
        <span class="price-label"><?php echo Mage::helper('wishlist')->__('Configured Price:') ?></span>
        <span class="price"><?php echo Mage::helper('core')->currency($finalPrice, true, false); ?></span>
    </p>
<?php endif; ?>
