<?php 
$chosen_category = Mage::getModel('catalog/category')->load($this->getCategoryId());
$_productCollection = $this->getLoadedProductCollection();
$number_of_products = $this->getNumProducts();
if (sizeof($_productCollection) < $number_of_products) {
	$number_of_products = sizeof($_productCollection);
}
$displayed_products = array();
foreach ($_productCollection as $_product) {
	$displayed_products[] = $_product;
}
$random_products = array();
if (sizeof($_productCollection) > 1) {
	$random_products = array_rand($displayed_products, $number_of_products);
} else {
	$random_products = array('0');
}
?>
<?php if(!$_productCollection->getSize()):?>
<div class="note-msg">
    <?=$this->__('There are no products matching the selection.')?>
</div>
<?php else:?>

<div class="random-products">
  <div class="page-title">
    <h1 class="page-title1"><?php echo $this->__('Random Products') ?></h1>
	</div>
  <div class="category-products">
    <table id="products-grid-table" class="products-grid-best">
	<?php 
	$k=0;
	for ($i=0; $i < $number_of_products; $i++): ?>
	<?php if ($k == 0) { ?>
			<tr class="first odd">
		<?php } if($k==4)	{ $k=0;  ?> 
			</tr><tr class="first odd even">
		<?php } ?>
        	<td id="td_<?php echo ($k+1); ?>" <?php if($k==4){ ?>class="last"<? } ?> >
              <div id="cont_<?php echo ($k+1); ?>">
              <div class="new_prod">
												 	
				  <div class="new_prod_image">			
				<a class="product-image" href="<?php echo $displayed_products[$random_products[$i]]->getProductUrl()?>"> <img src="<?php echo $this->helper('catalog/image')->init($displayed_products[$random_products[$i]], 'small_image')->resize(140);?>" alt="<?php echo $this->htmlEscape($displayed_products[$random_products[$i]]->getName())?>" title="<?php echo $this->htmlEscape($displayed_products[$random_products[$i]]->getName())?>"/> </a> 
				</div>
                <div class="product-name-block-random">                 
				  <?php
				  $pname=$this->htmlEscape($displayed_products[$random_products[$i]]->getName());
				  ?>
				<div class="new_product-name">				  
				  <a href="<?php echo $displayed_products[$random_products[$i]]->getProductUrl()?>" title="<?php echo $pname; ?>">
                    <?php if(strlen($pname) > 20) {echo substr($pname,0,15)."...";}else {echo $pname;}?>
                    </a></div>
                </div>
					<div class="new_prod_price">
					<div class="price-box">
					<span class="regular-price" id="product-price-37">						
						<span class="price" ><?php $rprice = $displayed_products[$random_products[$i]]->getPrice(); ?><?php echo  Mage::helper('core')->currency(number_format( $rprice,2));  ?></span>
					</span>
					</div>                      
				
<div class="new_prod_btn">	<?php if($_product->isSaleable()): ?>																												
					<button onclick="setLocation('<?php echo $this->getUrl('')."/checkout/cart/add?product=".$displayed_products[$random_products[$i]]->getId()."&qty=1"  ?>')" class="cartbutton" style="margin-left:15px !important;"><?php echo $this->__('Add to Cart') ?></button> 
		<?php else: ?>
	<p class="availability"><span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                    <div class="clear"></div>
                <?php endif; ?>
				</div></div>
              </div>
        </div>
		 <div class="clear"></div></td>	

<?php $k++; ?>
<?php endfor;?>
</tr>
      </table>     
    </div>
</div>		
<?php endif;?> 
