<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php endif ?>
<?php echo $this->getToolbarHtml() ?>
<?php // List mode ?>
<div class="list_view_container category-products" style="display: none;">


    <?php foreach ($_productCollection as $_product): ?>


        <div class="single_product_division">
            <div class="product_image">
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                   class="product-image"><img
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>"
                        width="135" height="200"
                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
            </div>
            <div class="product_desc">
                <h5 class="product_name">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $_productNameStripped; ?>">
                           <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                    </a>
                </h5>
                <span class="product_sub_text"> 
                    <!-- Get Key ingredients --> <?php
                    $product_details = Mage::getModel('catalog/product')->load($_product->getId());
                    if ($product_details->getKeyingredient()):
                        ?> 
                        <?php
                        $str = nl2br($product_details->getKeyingredient());
                        echo substr($str, 0, 50);
                        ?>...
                    <?php endif; ?> <!-- End Get Key ingredients -->
                </span>
                <p class="product_detail_text">
                    <?php
                    $str = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                    echo substr($str, 0, 280);
                    ?>
                    ....
                </p>
                <div class="product_price">
                    <div class="left">
                        <?php
                        $product = Mage::getModel('catalog/product')->load($_product->getId());
                        $price = $product->getPrice();
                        $webprice = $product->getwebprice();
                        $specialprice = $product->getFinalPrice();
                        $_finalPriceInclTax = Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);
                        $fxdTax = $product->getFixedTax();
                        $fxdTaxrate = $fxdTax[0]['value'];
                        $taxrate = $_product->getData('tax_percent');
                        $fixedtax_amount = $fxdTaxrate * $taxrate;
                        $_finalPriceInclTax = $_finalPriceInclTax + $fixedtax_amount + $fxdTaxrate;


                        if ($specialprice == $price) {
                            ?>
                            <span class="regular_price"><?php echo $this->__('Regular Price'); ?> : <span> Dkr<?php echo number_format($_finalPriceInclTax, 2); ?>
                                </span>
                            </span>                     
                            <span class="special_price"><?php echo $this->__('Special Price'); ?> : <span>Dkr 00.00</span>
                            </span>
<!--                            <span class="exclude_tax">(<?php //echo $this->__('Excluding vat'); ?>: <span>Dkr <?php //echo number_format($price, 2); ?>)</span></span>-->
                        <?php } elseif ($specialprice < $price) { ?>
                            <span class="regular_price"><?php echo $this->__('Regular Price'); ?> : <span> Dkr<?php echo number_format($_finalPriceInclTax, 2); ?>
                                </span>
                            </span> <span class="special_price"><?php echo $this->__('Special Price'); ?> : <span>Dkr <?php echo number_format($specialprice, 2); ?>
                                </span>
                            </span>
                            <span class="exclude_tax">( Price excluding tax: <span>Dkr <?php echo number_format($price, 2); ?>)</span></span>
                        <?php } ?>

                    </div>
                    <div class="right">

                        <a href="<?php echo $_product->getProductUrl() ?>"
                           class="product_view_more"><?php echo $this->__('View More'); ?></a> <a
                           class="product_add_to_cart"
                           onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <?php echo $this->__('Add to Cart'); ?></a>
                    </div>
                    <div class="clear"></div>
                </div>
                <a href="" class="review_product_link"><?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                </a>
            </div>

        </div>

    <?php endforeach ?>



</div>

<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>



<div class="clear"></div>





<?php // Grid Mode  ?>
<div class="grid_view_container">

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php
    $i = 0;
    foreach ($_productCollection as $_product):
        ?>



        <div class="single_product_division">
            <span class="product_image"> <a
                    href="<?php echo $_product->getProductUrl() ?>"
                    title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                    class="product-image"><img
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>"
                        width="135" height="190"
                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
            </span>
            <h5 class="product_name">
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                       <?php
                       $str = $_helper->productAttribute($_product, $_product->getName(), 'name');
                       (strlen($str) > 40) ? $name = substr($str, 0, 40) . '...' : $name = $str;
                       echo $name;
                       ?>
                </a>
            </h5>
            <span class="product_sub_text"> 

                <!-- Get Key ingredients --> 
                <?php
                $product_details = Mage::getModel('catalog/product')->load($_product->getId());
                if ($product_details->getKeyingredient()):
                    ?> 
                    <?php
                    $str = nl2br($product_details->getKeyingredient());
                    echo substr($str, 0, 33);
                    ?> <?php endif; ?>

                <!-- End Get Key ingredients -->

            </span> <span class="product_price"> <?php
                $product = Mage::getModel('catalog/product')->load($_product->getId());
                $specialprice = $product->combo_price;
                $price = $product->getPrice();
                $webprice = $product->getwebprice();
                $tax = $product->getTaxRate();

                $_finalPriceInclTax = Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);

                $fxdTax = $product->getFixedTax();
                $fxdTaxrate = $fxdTax[0]['value'];
                $taxrate = $_product->getData('tax_percent');
                $fixedtax_amount = $fxdTaxrate * $taxrate;
                $_finalPriceInclTax = $_finalPriceInclTax + $fixedtax_amount + $fxdTaxrate;

                $combopriceWithFixedTax = $specialprice + $fxdTaxrate;
                $combopriceWithTax = $combopriceWithFixedTax + ($combopriceWithFixedTax * $taxrate );
                ?>
                <span class="regular_price"><?php echo $this->__('Regular Price'); ?> : <span> Dkr<?php echo number_format($_finalPriceInclTax, 2); ?>
                    </span>               
                </span>               
                <span class="special_price"><?php echo $this->__('Special Price'); ?> : 
                    <span>Dkr <?php echo number_format($combopriceWithTax, 2); ?></span>
                </span> 
<!--                <span class="exclude_tax">(<?php //echo $this->__('Excluding vat'); ?>: Dkr <span><?php //echo number_format($price, 2); ?>)</span></span>-->
            </span> <a href="" class="review_product_link"> <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
            </a> <span class="product_links_content"> <a
                    href="<?php echo $_product->getProductUrl() ?>"
                    class="product_view_more"
                    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->__('View More'); ?></a> <a class="product_add_to_cart"
                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart'); ?></a>
            </span>
        </div>
    <?php endforeach ?>
    <div class="clear"></div>
</div>
<?php
$toolbar = new Mage_Catalog_Block_Product_List_Toolbar();
$pager = new Mage_Page_Block_Html_Pager();
$pager->setAvailableLimit($toolbar->getAvailableLimit());
$pager->setCollection($_productCollection); // or another variable that contains collection
echo $pager->_toHtml();
?>
