<br />
<div class="box-account box-tags">
    <div class="box-head">
        <h3><?php echo $this->__('My Recent Tags') ?></h3>
        <a style="float:right;" href="<?php echo $this->getAllTagsUrl() ?>"><?php echo $this->__('View All Tags') ?></a>
    </div>
    <ol id="my_recent_tags">
        <?php $iterator = 0; ?>
        <?php foreach( $this->getCollection()->getItems() as $_item ): ?>
            <li class="item">
                <span class="number"><?php echo ++$iterator ?></span>
                <div class="details">
                    <h5 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h5>
                    <div class="tags">
                        <strong><?php echo $this->__('Tags:') ?></strong>
                        <?php $_i = 0; ?>
                        <ul>
                        <?php foreach( $_item->getProductTags() as $_tag ): ?>
                            <li><a href="<?php echo $_tag->getViewTagUrl() ?>"><?php echo $this->htmlEscape($_tag->getName()) ?></a><?php if(++$_i != sizeof($_item->getProductTags()->getItems())): ?>,<?php endif; ?></li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('my_recent_tags', 'none-recursive');</script>
</div>
