
<div class="page-title_a">
    <h2 class="page-title_a"><?php echo $this->__('Forgot Your Password?') ?></h2>
</div>
<div class="dashboard">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <fieldset class="col2-set login-page">
    <h3 class="heading"><?php echo $this->__('Retrieve your password here') ?></h3>
    <div class="content">
        
        <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address"><?php echo $this->__('Email Address') ?><span class="required">*</span></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
    
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
        
    </div>
    </div></fieldset>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
