<div class="col-main1">
<div class="page-title_a">
        <h2 class="page-title_a"><?php echo $this->__('Login or Create an Account') ?></h2>
    </div>
<!--div class="account-login"-->
   <div class="form_background"> 
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
     <fieldset class="col2-set login-page">
        <!--div class="col2-set"-->
            <div class="col-1a new-users">
		<h3 class="heading"><?php echo $this->__('New Customers') ?></h3>
                <div class="content">
                    
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>

		    <div class="buttons-set" style="margin-top:68px;">
                    <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                </div>

                </div>
            </div>
            <div class="col-2a registered-users">
		<h3 class="heading"><?php echo $this->__('Registered Customers') ?></h3>
                <div class="content">
                    
                    <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email"><?php echo $this->__('Email Address') ?><span class="required">*</span></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass"><?php echo $this->__('Password') ?><span class="required">*</span></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
		  <div class="buttons-set1">
                   
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
		     <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
                </div>
            </div>
        <!--/div-->
       
      </fieldset>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
<!--/div-->
</div>
