<?php /* $_helper = Mage::helper('catalog/category') ?>
  <?php $_categories = $_helper->getStoreCategories() ?>
  <?php if (count($_categories) > 0): ?>

  <?php foreach($_categories as $_category): ?>
  <li>
  <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
  <?php echo $_category->getName() ?>
  </a>
  </li>
  <?php endforeach; ?>

  <?php endif; */ ?>
<?php
$categoryId = 46;
$category = Mage::getModel('catalog/category')->load($categoryId);
 $path = $category->getUrl();
 //default-category.html
?>
<li><a href="<?php echo $path; ?>"><?php echo $this->__('Products'); ?></a></li>
<li><a href="<?php echo $this->getUrl('') ?>about-us"><?php echo $this->__('About Us'); ?></a></li>
<li><a href="<?php echo $this->getUrl('') ?>our-services"> <?php echo $this->__('Our Services'); ?></a></li>
<li><a href="<?php echo $this->getUrl('') ?>contact-us"><?php echo $this->__('Contact Us'); ?> </a></li>
