<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
   <fieldset class="form-search">
        <!--label for="search"><?php //echo $this->__('Search') ?></label-->
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text" /><input border="0" type="image" title="Search" alt="Search" src="<?php echo $this->getSkinUrl('images/search_btn.png'); ?>">
        <!--button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><?php echo $this->__('Go') ?></span></button-->
       
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search here...') ?>');
            searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
   </fieldset>
</form>


