<div class="page-title_a">
   <h2 class="page-title_a"><?php echo $this->__('Popular Search Terms') ?></h2>
</div>
<div class="dashboard">
<?php if( sizeof($this->getTerms()) > 0 ): ?>
    <ul class="tags-list">
        <?php foreach ($this->getTerms() as $_term): ?>
            <li><a href="<?php echo $this->getSearchUrl($_term) ?>" style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_term->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no search terms available.'); ?></p>
<?php endif; ?>
</div>
