<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<div class="cross_sell_prod">
<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h3><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h3>
   <div class="category-products"> <ul id="crosssell-products-list" class="products-grid">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item"><div class="new_prod">
              <div class="new_prod_image"><a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(125,135); ?>" width="125" height="135" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
		</div>
            <div class="product-name-block">
        <div class="new_product-name"><h7><a href="<?php echo $_item->getProductUrl() ?>">
	<?php $prod_name = $this->htmlEscape($_item->getName());  if(strlen($prod_name) > 20) {echo substr($prod_name,0,18)."...";}else {echo $prod_name;}?>
	</a></h7></div>
               <div class="new_prod_price"> <?php echo $this->getPriceHtml($_item, true) ?></div>
               <div class="new_prod_btn"> <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
            
       </div> </div></li>
    <?php endforeach; ?>
    </ul></div>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
</div>
