<div class="page-title_a">
    <h2 class="page-title_a"><?php echo $this->__('Shopping Cart is Empty') ?></h2>
</div><div class="form_background12">
<div class="cart-empty">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
</div></div>
