<div class="page-title_a">
    <h2 class="page-title_a"><?php echo $this->__('Recurring Profiles') ?></h2>
</div>
<div class="dashboard">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="recurring-profiles">

    <?php echo $this->getChildHtml('grid')?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</div></div>
