



<!--   <h5 class="price_range_head">Select your price range</h5>
   <input type="text" id="price_range" name="rangeName" value=""/>-->
<br/>
<center>
<!--<img src="<?php echo $this->getSkinUrl('images/adv_banner.jpg'); ?>" alt="" />-->
    <div class="special_price_adv">
        <div class="spa_top">
            <span class="spa_1">18</span>
            <span class="spa_2"><?php echo $this->__('ADD BOTTLES TO YOUR CART'); ?></span>
        </div>
        <div class="spa_bottom">
            <span class="spa_1"><?php echo $this->__('GET A'); ?></span>
            <span class="spa_2"><?php echo $this->__('SPECIAL PRICE'); ?></span>
        </div>

    </div>
</center>
<br/>







